#-------------------------------------------------
#
# Project created by QtCreator 2016-10-27T10:13:33
#
#-------------------------------------------------

QT       -= core gui
TARGET = zcommon
TEMPLATE = lib
CONFIG += staticlib
unix {
    target.path = /usr/lib
    INSTALLS += target
}



HEADERS += \
    include/msgpack/msgpack/adaptor/boost/fusion.hpp \
    include/msgpack/msgpack/adaptor/boost/msgpack_variant.hpp \
    include/msgpack/msgpack/adaptor/boost/optional.hpp \
    include/msgpack/msgpack/adaptor/boost/string_ref.hpp \
    include/msgpack/msgpack/adaptor/cpp11/array.hpp \
    include/msgpack/msgpack/adaptor/cpp11/array_char.hpp \
    include/msgpack/msgpack/adaptor/cpp11/array_unsigned_char.hpp \
    include/msgpack/msgpack/adaptor/cpp11/forward_list.hpp \
    include/msgpack/msgpack/adaptor/cpp11/reference_wrapper.hpp \
    include/msgpack/msgpack/adaptor/cpp11/shared_ptr.hpp \
    include/msgpack/msgpack/adaptor/cpp11/tuple.hpp \
    include/msgpack/msgpack/adaptor/cpp11/unique_ptr.hpp \
    include/msgpack/msgpack/adaptor/cpp11/unordered_map.hpp \
    include/msgpack/msgpack/adaptor/cpp11/unordered_set.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp03_define_array.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp03_define_map.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp11_define_array.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp11_define_map.hpp \
    include/msgpack/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp \
    include/msgpack/msgpack/adaptor/tr1/unordered_map.hpp \
    include/msgpack/msgpack/adaptor/tr1/unordered_set.hpp \
    include/msgpack/msgpack/adaptor/adaptor_base.hpp \
    include/msgpack/msgpack/adaptor/array_ref.hpp \
    include/msgpack/msgpack/adaptor/bool.hpp \
    include/msgpack/msgpack/adaptor/char_ptr.hpp \
    include/msgpack/msgpack/adaptor/check_container_size.hpp \
    include/msgpack/msgpack/adaptor/define.hpp \
    include/msgpack/msgpack/adaptor/deque.hpp \
    include/msgpack/msgpack/adaptor/ext.hpp \
    include/msgpack/msgpack/adaptor/fixint.hpp \
    include/msgpack/msgpack/adaptor/float.hpp \
    include/msgpack/msgpack/adaptor/int.hpp \
    include/msgpack/msgpack/adaptor/list.hpp \
    include/msgpack/msgpack/adaptor/map.hpp \
    include/msgpack/msgpack/adaptor/msgpack_tuple.hpp \
    include/msgpack/msgpack/adaptor/nil.hpp \
    include/msgpack/msgpack/adaptor/pair.hpp \
    include/msgpack/msgpack/adaptor/raw.hpp \
    include/msgpack/msgpack/adaptor/set.hpp \
    include/msgpack/msgpack/adaptor/string.hpp \
    include/msgpack/msgpack/adaptor/v4raw.hpp \
    include/msgpack/msgpack/adaptor/vector.hpp \
    include/msgpack/msgpack/adaptor/vector_bool.hpp \
    include/msgpack/msgpack/adaptor/vector_char.hpp \
    include/msgpack/msgpack/adaptor/vector_unsigned_char.hpp \
    include/msgpack/msgpack/detail/cpp03_zone.hpp \
    include/msgpack/msgpack/detail/cpp11_zone.hpp \
    include/msgpack/msgpack/predef/architecture/x86/32.h \
    include/msgpack/msgpack/predef/architecture/x86/64.h \
    include/msgpack/msgpack/predef/architecture/alpha.h \
    include/msgpack/msgpack/predef/architecture/arm.h \
    include/msgpack/msgpack/predef/architecture/blackfin.h \
    include/msgpack/msgpack/predef/architecture/convex.h \
    include/msgpack/msgpack/predef/architecture/ia64.h \
    include/msgpack/msgpack/predef/architecture/m68k.h \
    include/msgpack/msgpack/predef/architecture/mips.h \
    include/msgpack/msgpack/predef/architecture/parisc.h \
    include/msgpack/msgpack/predef/architecture/ppc.h \
    include/msgpack/msgpack/predef/architecture/pyramid.h \
    include/msgpack/msgpack/predef/architecture/rs6k.h \
    include/msgpack/msgpack/predef/architecture/sparc.h \
    include/msgpack/msgpack/predef/architecture/superh.h \
    include/msgpack/msgpack/predef/architecture/sys370.h \
    include/msgpack/msgpack/predef/architecture/sys390.h \
    include/msgpack/msgpack/predef/architecture/x86.h \
    include/msgpack/msgpack/predef/architecture/z.h \
    include/msgpack/msgpack/predef/compiler/borland.h \
    include/msgpack/msgpack/predef/compiler/clang.h \
    include/msgpack/msgpack/predef/compiler/comeau.h \
    include/msgpack/msgpack/predef/compiler/compaq.h \
    include/msgpack/msgpack/predef/compiler/diab.h \
    include/msgpack/msgpack/predef/compiler/digitalmars.h \
    include/msgpack/msgpack/predef/compiler/dignus.h \
    include/msgpack/msgpack/predef/compiler/edg.h \
    include/msgpack/msgpack/predef/compiler/ekopath.h \
    include/msgpack/msgpack/predef/compiler/gcc.h \
    include/msgpack/msgpack/predef/compiler/gcc_xml.h \
    include/msgpack/msgpack/predef/compiler/greenhills.h \
    include/msgpack/msgpack/predef/compiler/hp_acc.h \
    include/msgpack/msgpack/predef/compiler/iar.h \
    include/msgpack/msgpack/predef/compiler/ibm.h \
    include/msgpack/msgpack/predef/compiler/intel.h \
    include/msgpack/msgpack/predef/compiler/kai.h \
    include/msgpack/msgpack/predef/compiler/llvm.h \
    include/msgpack/msgpack/predef/compiler/metaware.h \
    include/msgpack/msgpack/predef/compiler/metrowerks.h \
    include/msgpack/msgpack/predef/compiler/microtec.h \
    include/msgpack/msgpack/predef/compiler/mpw.h \
    include/msgpack/msgpack/predef/compiler/palm.h \
    include/msgpack/msgpack/predef/compiler/pgi.h \
    include/msgpack/msgpack/predef/compiler/sgi_mipspro.h \
    include/msgpack/msgpack/predef/compiler/sunpro.h \
    include/msgpack/msgpack/predef/compiler/tendra.h \
    include/msgpack/msgpack/predef/compiler/visualc.h \
    include/msgpack/msgpack/predef/compiler/watcom.h \
    include/msgpack/msgpack/predef/detail/_cassert.h \
    include/msgpack/msgpack/predef/detail/_exception.h \
    include/msgpack/msgpack/predef/detail/comp_detected.h \
    include/msgpack/msgpack/predef/detail/endian_compat.h \
    include/msgpack/msgpack/predef/detail/os_detected.h \
    include/msgpack/msgpack/predef/detail/platform_detected.h \
    include/msgpack/msgpack/predef/detail/test.h \
    include/msgpack/msgpack/predef/language/objc.h \
    include/msgpack/msgpack/predef/language/stdc.h \
    include/msgpack/msgpack/predef/language/stdcpp.h \
    include/msgpack/msgpack/predef/library/c/_prefix.h \
    include/msgpack/msgpack/predef/library/c/gnu.h \
    include/msgpack/msgpack/predef/library/c/uc.h \
    include/msgpack/msgpack/predef/library/c/vms.h \
    include/msgpack/msgpack/predef/library/c/zos.h \
    include/msgpack/msgpack/predef/library/std/_prefix.h \
    include/msgpack/msgpack/predef/library/std/cxx.h \
    include/msgpack/msgpack/predef/library/std/dinkumware.h \
    include/msgpack/msgpack/predef/library/std/libcomo.h \
    include/msgpack/msgpack/predef/library/std/modena.h \
    include/msgpack/msgpack/predef/library/std/msl.h \
    include/msgpack/msgpack/predef/library/std/roguewave.h \
    include/msgpack/msgpack/predef/library/std/sgi.h \
    include/msgpack/msgpack/predef/library/std/stdcpp3.h \
    include/msgpack/msgpack/predef/library/std/stlport.h \
    include/msgpack/msgpack/predef/library/std/vacpp.h \
    include/msgpack/msgpack/predef/library/c.h \
    include/msgpack/msgpack/predef/library/std.h \
    include/msgpack/msgpack/predef/os/bsd/bsdi.h \
    include/msgpack/msgpack/predef/os/bsd/dragonfly.h \
    include/msgpack/msgpack/predef/os/bsd/free.h \
    include/msgpack/msgpack/predef/os/bsd/net.h \
    include/msgpack/msgpack/predef/os/bsd/open.h \
    include/msgpack/msgpack/predef/os/aix.h \
    include/msgpack/msgpack/predef/os/amigaos.h \
    include/msgpack/msgpack/predef/os/android.h \
    include/msgpack/msgpack/predef/os/beos.h \
    include/msgpack/msgpack/predef/os/bsd.h \
    include/msgpack/msgpack/predef/os/cygwin.h \
    include/msgpack/msgpack/predef/os/haiku.h \
    include/msgpack/msgpack/predef/os/hpux.h \
    include/msgpack/msgpack/predef/os/ios.h \
    include/msgpack/msgpack/predef/os/irix.h \
    include/msgpack/msgpack/predef/os/linux.h \
    include/msgpack/msgpack/predef/os/macos.h \
    include/msgpack/msgpack/predef/os/os400.h \
    include/msgpack/msgpack/predef/os/qnxnto.h \
    include/msgpack/msgpack/predef/os/solaris.h \
    include/msgpack/msgpack/predef/os/unix.h \
    include/msgpack/msgpack/predef/os/vms.h \
    include/msgpack/msgpack/predef/os/windows.h \
    include/msgpack/msgpack/predef/other/endian.h \
    include/msgpack/msgpack/predef/platform/mingw.h \
    include/msgpack/msgpack/predef/platform/windows_desktop.h \
    include/msgpack/msgpack/predef/platform/windows_phone.h \
    include/msgpack/msgpack/predef/platform/windows_runtime.h \
    include/msgpack/msgpack/predef/platform/windows_store.h \
    include/msgpack/msgpack/predef/architecture.h \
    include/msgpack/msgpack/predef/compiler.h \
    include/msgpack/msgpack/predef/language.h \
    include/msgpack/msgpack/predef/library.h \
    include/msgpack/msgpack/predef/make.h \
    include/msgpack/msgpack/predef/os.h \
    include/msgpack/msgpack/predef/other.h \
    include/msgpack/msgpack/predef/platform.h \
    include/msgpack/msgpack/predef/version.h \
    include/msgpack/msgpack/predef/version_number.h \
    include/msgpack/msgpack/preprocessor/arithmetic/detail/div_base.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/add.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/dec.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/div.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/inc.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/mod.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/mul.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic/sub.hpp \
    include/msgpack/msgpack/preprocessor/array/detail/get_data.hpp \
    include/msgpack/msgpack/preprocessor/array/data.hpp \
    include/msgpack/msgpack/preprocessor/array/elem.hpp \
    include/msgpack/msgpack/preprocessor/array/enum.hpp \
    include/msgpack/msgpack/preprocessor/array/insert.hpp \
    include/msgpack/msgpack/preprocessor/array/pop_back.hpp \
    include/msgpack/msgpack/preprocessor/array/pop_front.hpp \
    include/msgpack/msgpack/preprocessor/array/push_back.hpp \
    include/msgpack/msgpack/preprocessor/array/push_front.hpp \
    include/msgpack/msgpack/preprocessor/array/remove.hpp \
    include/msgpack/msgpack/preprocessor/array/replace.hpp \
    include/msgpack/msgpack/preprocessor/array/reverse.hpp \
    include/msgpack/msgpack/preprocessor/array/size.hpp \
    include/msgpack/msgpack/preprocessor/array/to_list.hpp \
    include/msgpack/msgpack/preprocessor/array/to_seq.hpp \
    include/msgpack/msgpack/preprocessor/array/to_tuple.hpp \
    include/msgpack/msgpack/preprocessor/comparison/equal.hpp \
    include/msgpack/msgpack/preprocessor/comparison/greater.hpp \
    include/msgpack/msgpack/preprocessor/comparison/greater_equal.hpp \
    include/msgpack/msgpack/preprocessor/comparison/less.hpp \
    include/msgpack/msgpack/preprocessor/comparison/less_equal.hpp \
    include/msgpack/msgpack/preprocessor/comparison/not_equal.hpp \
    include/msgpack/msgpack/preprocessor/config/config.hpp \
    include/msgpack/msgpack/preprocessor/config/limits.hpp \
    include/msgpack/msgpack/preprocessor/control/detail/dmc/while.hpp \
    include/msgpack/msgpack/preprocessor/control/detail/edg/while.hpp \
    include/msgpack/msgpack/preprocessor/control/detail/msvc/while.hpp \
    include/msgpack/msgpack/preprocessor/control/detail/while.hpp \
    include/msgpack/msgpack/preprocessor/control/deduce_d.hpp \
    include/msgpack/msgpack/preprocessor/control/expr_if.hpp \
    include/msgpack/msgpack/preprocessor/control/expr_iif.hpp \
    include/msgpack/msgpack/preprocessor/control/if.hpp \
    include/msgpack/msgpack/preprocessor/control/iif.hpp \
    include/msgpack/msgpack/preprocessor/control/while.hpp \
    include/msgpack/msgpack/preprocessor/debug/assert.hpp \
    include/msgpack/msgpack/preprocessor/debug/error.hpp \
    include/msgpack/msgpack/preprocessor/debug/line.hpp \
    include/msgpack/msgpack/preprocessor/detail/dmc/auto_rec.hpp \
    include/msgpack/msgpack/preprocessor/detail/auto_rec.hpp \
    include/msgpack/msgpack/preprocessor/detail/check.hpp \
    include/msgpack/msgpack/preprocessor/detail/is_binary.hpp \
    include/msgpack/msgpack/preprocessor/detail/is_nullary.hpp \
    include/msgpack/msgpack/preprocessor/detail/is_unary.hpp \
    include/msgpack/msgpack/preprocessor/detail/null.hpp \
    include/msgpack/msgpack/preprocessor/detail/split.hpp \
    include/msgpack/msgpack/preprocessor/facilities/detail/is_empty.hpp \
    include/msgpack/msgpack/preprocessor/facilities/apply.hpp \
    include/msgpack/msgpack/preprocessor/facilities/empty.hpp \
    include/msgpack/msgpack/preprocessor/facilities/expand.hpp \
    include/msgpack/msgpack/preprocessor/facilities/identity.hpp \
    include/msgpack/msgpack/preprocessor/facilities/intercept.hpp \
    include/msgpack/msgpack/preprocessor/facilities/is_1.hpp \
    include/msgpack/msgpack/preprocessor/facilities/is_empty.hpp \
    include/msgpack/msgpack/preprocessor/facilities/is_empty_or_1.hpp \
    include/msgpack/msgpack/preprocessor/facilities/is_empty_variadic.hpp \
    include/msgpack/msgpack/preprocessor/facilities/overload.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/lower1.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/lower2.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/lower3.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/lower4.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/lower5.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/upper1.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/upper2.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/upper3.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/upper4.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/bounds/upper5.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/forward1.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/forward2.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/forward3.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/forward4.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/forward5.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/reverse1.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/reverse2.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/reverse3.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/reverse4.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/iter/reverse5.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/finish.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/local.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/rlocal.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/self.hpp \
    include/msgpack/msgpack/preprocessor/iteration/detail/start.hpp \
    include/msgpack/msgpack/preprocessor/iteration/iterate.hpp \
    include/msgpack/msgpack/preprocessor/iteration/local.hpp \
    include/msgpack/msgpack/preprocessor/iteration/self.hpp \
    include/msgpack/msgpack/preprocessor/list/detail/dmc/fold_left.hpp \
    include/msgpack/msgpack/preprocessor/list/detail/edg/fold_left.hpp \
    include/msgpack/msgpack/preprocessor/list/detail/edg/fold_right.hpp \
    include/msgpack/msgpack/preprocessor/list/detail/fold_left.hpp \
    include/msgpack/msgpack/preprocessor/list/detail/fold_right.hpp \
    include/msgpack/msgpack/preprocessor/list/adt.hpp \
    include/msgpack/msgpack/preprocessor/list/append.hpp \
    include/msgpack/msgpack/preprocessor/list/at.hpp \
    include/msgpack/msgpack/preprocessor/list/cat.hpp \
    include/msgpack/msgpack/preprocessor/list/enum.hpp \
    include/msgpack/msgpack/preprocessor/list/filter.hpp \
    include/msgpack/msgpack/preprocessor/list/first_n.hpp \
    include/msgpack/msgpack/preprocessor/list/fold_left.hpp \
    include/msgpack/msgpack/preprocessor/list/fold_right.hpp \
    include/msgpack/msgpack/preprocessor/list/for_each.hpp \
    include/msgpack/msgpack/preprocessor/list/for_each_i.hpp \
    include/msgpack/msgpack/preprocessor/list/for_each_product.hpp \
    include/msgpack/msgpack/preprocessor/list/rest_n.hpp \
    include/msgpack/msgpack/preprocessor/list/reverse.hpp \
    include/msgpack/msgpack/preprocessor/list/size.hpp \
    include/msgpack/msgpack/preprocessor/list/to_array.hpp \
    include/msgpack/msgpack/preprocessor/list/to_seq.hpp \
    include/msgpack/msgpack/preprocessor/list/to_tuple.hpp \
    include/msgpack/msgpack/preprocessor/list/transform.hpp \
    include/msgpack/msgpack/preprocessor/logical/and.hpp \
    include/msgpack/msgpack/preprocessor/logical/bitand.hpp \
    include/msgpack/msgpack/preprocessor/logical/bitnor.hpp \
    include/msgpack/msgpack/preprocessor/logical/bitor.hpp \
    include/msgpack/msgpack/preprocessor/logical/bitxor.hpp \
    include/msgpack/msgpack/preprocessor/logical/bool.hpp \
    include/msgpack/msgpack/preprocessor/logical/compl.hpp \
    include/msgpack/msgpack/preprocessor/logical/nor.hpp \
    include/msgpack/msgpack/preprocessor/logical/not.hpp \
    include/msgpack/msgpack/preprocessor/logical/or.hpp \
    include/msgpack/msgpack/preprocessor/logical/xor.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/detail/is_begin_parens.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/comma.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/comma_if.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/is_begin_parens.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/paren.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/paren_if.hpp \
    include/msgpack/msgpack/preprocessor/punctuation/remove_parens.hpp \
    include/msgpack/msgpack/preprocessor/repetition/detail/dmc/for.hpp \
    include/msgpack/msgpack/preprocessor/repetition/detail/edg/for.hpp \
    include/msgpack/msgpack/preprocessor/repetition/detail/msvc/for.hpp \
    include/msgpack/msgpack/preprocessor/repetition/detail/for.hpp \
    include/msgpack/msgpack/preprocessor/repetition/deduce_r.hpp \
    include/msgpack/msgpack/preprocessor/repetition/deduce_z.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_binary_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_params_with_a_default.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_params_with_defaults.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_shifted.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_shifted_binary_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_shifted_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_trailing.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_trailing_binary_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/enum_trailing_params.hpp \
    include/msgpack/msgpack/preprocessor/repetition/for.hpp \
    include/msgpack/msgpack/preprocessor/repetition/repeat.hpp \
    include/msgpack/msgpack/preprocessor/repetition/repeat_from_to.hpp \
    include/msgpack/msgpack/preprocessor/selection/max.hpp \
    include/msgpack/msgpack/preprocessor/selection/min.hpp \
    include/msgpack/msgpack/preprocessor/seq/detail/binary_transform.hpp \
    include/msgpack/msgpack/preprocessor/seq/detail/split.hpp \
    include/msgpack/msgpack/preprocessor/seq/cat.hpp \
    include/msgpack/msgpack/preprocessor/seq/elem.hpp \
    include/msgpack/msgpack/preprocessor/seq/enum.hpp \
    include/msgpack/msgpack/preprocessor/seq/filter.hpp \
    include/msgpack/msgpack/preprocessor/seq/first_n.hpp \
    include/msgpack/msgpack/preprocessor/seq/fold_left.hpp \
    include/msgpack/msgpack/preprocessor/seq/fold_right.hpp \
    include/msgpack/msgpack/preprocessor/seq/for_each.hpp \
    include/msgpack/msgpack/preprocessor/seq/for_each_i.hpp \
    include/msgpack/msgpack/preprocessor/seq/for_each_product.hpp \
    include/msgpack/msgpack/preprocessor/seq/insert.hpp \
    include/msgpack/msgpack/preprocessor/seq/pop_back.hpp \
    include/msgpack/msgpack/preprocessor/seq/pop_front.hpp \
    include/msgpack/msgpack/preprocessor/seq/push_back.hpp \
    include/msgpack/msgpack/preprocessor/seq/push_front.hpp \
    include/msgpack/msgpack/preprocessor/seq/remove.hpp \
    include/msgpack/msgpack/preprocessor/seq/replace.hpp \
    include/msgpack/msgpack/preprocessor/seq/rest_n.hpp \
    include/msgpack/msgpack/preprocessor/seq/reverse.hpp \
    include/msgpack/msgpack/preprocessor/seq/seq.hpp \
    include/msgpack/msgpack/preprocessor/seq/size.hpp \
    include/msgpack/msgpack/preprocessor/seq/subseq.hpp \
    include/msgpack/msgpack/preprocessor/seq/to_array.hpp \
    include/msgpack/msgpack/preprocessor/seq/to_list.hpp \
    include/msgpack/msgpack/preprocessor/seq/to_tuple.hpp \
    include/msgpack/msgpack/preprocessor/seq/transform.hpp \
    include/msgpack/msgpack/preprocessor/seq/variadic_seq_to_seq.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/counter.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/def.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/shared.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/slot1.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/slot2.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/slot3.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/slot4.hpp \
    include/msgpack/msgpack/preprocessor/slot/detail/slot5.hpp \
    include/msgpack/msgpack/preprocessor/slot/counter.hpp \
    include/msgpack/msgpack/preprocessor/slot/slot.hpp \
    include/msgpack/msgpack/preprocessor/tuple/detail/is_single_return.hpp \
    include/msgpack/msgpack/preprocessor/tuple/eat.hpp \
    include/msgpack/msgpack/preprocessor/tuple/elem.hpp \
    include/msgpack/msgpack/preprocessor/tuple/enum.hpp \
    include/msgpack/msgpack/preprocessor/tuple/insert.hpp \
    include/msgpack/msgpack/preprocessor/tuple/pop_back.hpp \
    include/msgpack/msgpack/preprocessor/tuple/pop_front.hpp \
    include/msgpack/msgpack/preprocessor/tuple/push_back.hpp \
    include/msgpack/msgpack/preprocessor/tuple/push_front.hpp \
    include/msgpack/msgpack/preprocessor/tuple/rem.hpp \
    include/msgpack/msgpack/preprocessor/tuple/remove.hpp \
    include/msgpack/msgpack/preprocessor/tuple/replace.hpp \
    include/msgpack/msgpack/preprocessor/tuple/reverse.hpp \
    include/msgpack/msgpack/preprocessor/tuple/size.hpp \
    include/msgpack/msgpack/preprocessor/tuple/to_array.hpp \
    include/msgpack/msgpack/preprocessor/tuple/to_list.hpp \
    include/msgpack/msgpack/preprocessor/tuple/to_seq.hpp \
    include/msgpack/msgpack/preprocessor/variadic/detail/is_single_return.hpp \
    include/msgpack/msgpack/preprocessor/variadic/elem.hpp \
    include/msgpack/msgpack/preprocessor/variadic/size.hpp \
    include/msgpack/msgpack/preprocessor/variadic/to_array.hpp \
    include/msgpack/msgpack/preprocessor/variadic/to_list.hpp \
    include/msgpack/msgpack/preprocessor/variadic/to_seq.hpp \
    include/msgpack/msgpack/preprocessor/variadic/to_tuple.hpp \
    include/msgpack/msgpack/preprocessor/arithmetic.hpp \
    include/msgpack/msgpack/preprocessor/array.hpp \
    include/msgpack/msgpack/preprocessor/assert_msg.hpp \
    include/msgpack/msgpack/preprocessor/cat.hpp \
    include/msgpack/msgpack/preprocessor/comma.hpp \
    include/msgpack/msgpack/preprocessor/comma_if.hpp \
    include/msgpack/msgpack/preprocessor/comparison.hpp \
    include/msgpack/msgpack/preprocessor/control.hpp \
    include/msgpack/msgpack/preprocessor/debug.hpp \
    include/msgpack/msgpack/preprocessor/dec.hpp \
    include/msgpack/msgpack/preprocessor/empty.hpp \
    include/msgpack/msgpack/preprocessor/enum.hpp \
    include/msgpack/msgpack/preprocessor/enum_params.hpp \
    include/msgpack/msgpack/preprocessor/enum_params_with_a_default.hpp \
    include/msgpack/msgpack/preprocessor/enum_params_with_defaults.hpp \
    include/msgpack/msgpack/preprocessor/enum_shifted.hpp \
    include/msgpack/msgpack/preprocessor/enum_shifted_params.hpp \
    include/msgpack/msgpack/preprocessor/expand.hpp \
    include/msgpack/msgpack/preprocessor/expr_if.hpp \
    include/msgpack/msgpack/preprocessor/facilities.hpp \
    include/msgpack/msgpack/preprocessor/for.hpp \
    include/msgpack/msgpack/preprocessor/identity.hpp \
    include/msgpack/msgpack/preprocessor/if.hpp \
    include/msgpack/msgpack/preprocessor/inc.hpp \
    include/msgpack/msgpack/preprocessor/iterate.hpp \
    include/msgpack/msgpack/preprocessor/iteration.hpp \
    include/msgpack/msgpack/preprocessor/library.hpp \
    include/msgpack/msgpack/preprocessor/limits.hpp \
    include/msgpack/msgpack/preprocessor/list.hpp \
    include/msgpack/msgpack/preprocessor/logical.hpp \
    include/msgpack/msgpack/preprocessor/max.hpp \
    include/msgpack/msgpack/preprocessor/min.hpp \
    include/msgpack/msgpack/preprocessor/punctuation.hpp \
    include/msgpack/msgpack/preprocessor/repeat.hpp \
    include/msgpack/msgpack/preprocessor/repeat_2nd.hpp \
    include/msgpack/msgpack/preprocessor/repeat_3rd.hpp \
    include/msgpack/msgpack/preprocessor/repeat_from_to.hpp \
    include/msgpack/msgpack/preprocessor/repeat_from_to_2nd.hpp \
    include/msgpack/msgpack/preprocessor/repeat_from_to_3rd.hpp \
    include/msgpack/msgpack/preprocessor/repetition.hpp \
    include/msgpack/msgpack/preprocessor/selection.hpp \
    include/msgpack/msgpack/preprocessor/seq.hpp \
    include/msgpack/msgpack/preprocessor/slot.hpp \
    include/msgpack/msgpack/preprocessor/stringize.hpp \
    include/msgpack/msgpack/preprocessor/tuple.hpp \
    include/msgpack/msgpack/preprocessor/variadic.hpp \
    include/msgpack/msgpack/preprocessor/while.hpp \
    include/msgpack/msgpack/preprocessor/wstringize.hpp \
    include/msgpack/msgpack/cpp_config.hpp \
    include/msgpack/msgpack/fbuffer.h \
    include/msgpack/msgpack/fbuffer.hpp \
    include/msgpack/msgpack/gcc_atomic.h \
    include/msgpack/msgpack/iterator.hpp \
    include/msgpack/msgpack/meta.hpp \
    include/msgpack/msgpack/object.h \
    include/msgpack/msgpack/object.hpp \
    include/msgpack/msgpack/object_fwd.hpp \
    include/msgpack/msgpack/pack.h \
    include/msgpack/msgpack/pack.hpp \
    include/msgpack/msgpack/pack_define.h \
    include/msgpack/msgpack/pack_template.h \
    include/msgpack/msgpack/predef.h \
    include/msgpack/msgpack/preprocessor.hpp \
    include/msgpack/msgpack/sbuffer.h \
    include/msgpack/msgpack/sbuffer.hpp \
    include/msgpack/msgpack/sysdep.h \
    include/msgpack/msgpack/type.hpp \
    include/msgpack/msgpack/unpack.h \
    include/msgpack/msgpack/unpack.hpp \
    include/msgpack/msgpack/unpack_define.h \
    include/msgpack/msgpack/unpack_template.h \
    include/msgpack/msgpack/util.h \
    include/msgpack/msgpack/version.h \
    include/msgpack/msgpack/version.hpp \
    include/msgpack/msgpack/version_master.h \
    include/msgpack/msgpack/versioning.hpp \
    include/msgpack/msgpack/vrefbuffer.h \
    include/msgpack/msgpack/vrefbuffer.hpp \
    include/msgpack/msgpack/zbuffer.h \
    include/msgpack/msgpack/zbuffer.hpp \
    include/msgpack/msgpack/zone.h \
    include/msgpack/msgpack/zone.hpp \
    include/msgpack/msgpack.h \
    include/msgpack/msgpack.hpp \
    include/zcommon/errorcode.h \
    include/zcommon/version.h \
    include/zcommon/zserviceinterface.h \
    src/zcommon/stringutil.h \
    src/zcommon/zdbkey.h \
    src/zcommon/zmemproxy.h \
    src/zcommon/zmemproxylocal.h \
    src/zcommon/zservicelocator.h \
    src/zcommon/common.h \
    include/zcommon/mysqlinit.h

SOURCES += \
    src/zcommon/stringutil.cpp \
    src/zcommon/zmemproxy.cpp \
    src/zcommon/zmemproxylocal.cpp \
    src/zcommon/zservicelocator.cpp \
    src/zcommon/common.cpp

INCLUDEPATH += /usr/local/include
LIBS += -L"/usr/local/lib" -lPocoFoundationd -lPocoJSONd -lPocoNetd -lPocoUtild -lPocoXMLd
LIBS += -L"/usr/local/lib" -lPocoFoundation -lPocoJSON -lPocoNet -lPocoUtil -lPocoXML
